# Generated by Django 5.1.7 on 2025-03-17 05:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Virtuals",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("hostname", models.CharField(max_length=32)),
                (
                    "protocol",
                    models.CharField(
                        choices=[("rdp", "RDP"), ("ssh", "SSH"), ("vnc", "VNC")],
                        max_length=5,
                    ),
                ),
                ("address", models.CharField(max_length=128)),
                ("port", models.IntegerField()),
                ("user_vm", models.CharField(max_length=64)),
                ("password_vm", models.CharField(max_length=128)),
                ("ignore_cert", models.BooleanField()),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Monitoring",
            fields=[
                ("monitoring_id", models.UUIDField(primary_key=True, serialize=False)),
                ("cpu_usage", models.FloatField()),
                ("memory_usage", models.FloatField()),
                ("network_traffic", models.TimeField()),
                ("monitoring_time", models.DateTimeField()),
                (
                    "virtual_machines",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.virtuals"
                    ),
                ),
            ],
        ),
    ]
